[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["RUF100", "RUF101", "RUF102", "PGH"]
preview = true

[tool.mypy]
ignore_missing_imports = true
allow_redefinition = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_defs = true
disallow_any_generics = true
strict_equality = true
strict_bytes = true
enable_error_code = [
    "redundant-cast",
    "possibly-undefined",
    "unused-awaitable",
    "truthy-iterable",
    "ignore-without-code",
    "unused-ignore",
]
exclude = ["venv"]
